server:
  address: localhost
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mapli?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=true&serverTimezone=Asia/Seoul
    username: root
    password: root4377

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update #개발 초기 단계라서 update (운영 DB에서는 사용하면 안 됨)
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        #open-in-view: false #OSIV 설정: 나중에 서비스 커지면 끄자

logging:
  level:
    org.hibernate.SQL: debug #JPA Hibernate가 생성하는 모든 SQL의 로그를 Logger를 이용해서 남김
    org.hibernate.type: trace #SQL 쿼리 파라미터를 로그로 남김